# Generated by Django 4.0.3 on 2022-03-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0003_item_interested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='no_of_items',
            new_name='items_ordered',
        ),
    ]
